### ISSUE TITLE
unable to get mojo test to pass in application with csrfprotect enabled

### ISSUE THREAD

**Issue by adam-stokes** [koorchik/Mojolicious-Plugin-CSRFProtect#3]
This is my test code : https://github.com/battlemidget/App-skryf/blob/master/t/web/00-app.t

And it fails here:

https://github.com/battlemidget/App-skryf/blob/master/t/web/00-app.t#L22-L27

I feel like im missing something when trying to process the form post when csrfprotect is enabled. Though when accessing via the browser everything works as expected.

Thanks!

**Comment by koorchik** [comment]
The main idea of CSRF Protection is requiring a secret, user-specific token in all form submissions and side-effect URLs prevents CSRF; the attacker's site cannot put the right token in its submissions.

So, when you enable Mojolicious::Plugin::CSRFProtect it will look for this token in all non GET/HEAD requests. When accessing via the browser everything works because you already have this token in a form ("form_for" helper adds it). If we are talking about AJAX then `<%= jquery_ajax_csrf_protection %>` helper places csrftoken in 'X-CSRF-Token' header.

So, you should add token to all your non GET/HEAD requests. You can try something like:

```
# Get token
my $csrftoken = $ua->get( '/' )->res->dom->at('meta[name=csrftoken]')->attrs('content')

# Add header with csrftoken to every request automatically
$t->ua->on(
    start => sub {
        my ( $ua, $tx ) = @_;
        $tx->req->headers->header( 'X-CSRF-Token', $csrftoken );
} );
```

**Comment by adam-stokes** [comment]
Thank you!! That worked perfectly and cleared up some confusion for me. :+1:

**Comment by vandrlexay** [comment]
Te solution above didn't help me, but this one was ok:
```
$t->ua->on(
    start => sub {
        my ( $ua, $tx ) = @_;
        $tx->req->cookies(@{ $ua->cookie_jar->all })
    } );

```

My version of Mojolicious is 7.19.

**Comment by skaurus** [comment]
And for me worked something like this:

```
$t->ua->on('start' => sub {
    my ($ua, $tx) = @_;
    return if not $t->tx;
    $ua->cookie_jar->collect($t->tx);
    $tx->req->cookies(map {
        Mojo::Cookie::Request->new($_)
    } @{ $ua->cookie_jar->all });
});
```

Mojolicious 8
